# Generated by Django 5.0.1 on 2024-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
