# Generated by Django 5.0.1 on 2024-01-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discription',
            field=models.CharField(max_length=100),
        ),
    ]
